### ISSUE TITLE
Couple questions :)

### ISSUE THREAD

**Issue by matsvandamme** [pmarchini/Esp32Dimmer#4]
Hi there!

Thanks very much for your work on this library. 

I intend this library together with the "QuickPID" library. The end goal is to control a high power heating element at mains voltage to control the temperature of an analog film developing process: https://en.m.wikipedia.org/wiki/C-41_process

Using the WiFi functionality of ESP32, I intend to have a control page hosted on the SoC so I control the process from my laptop.

I have the following questions regarding the proposed circuitry on the README page:

1) Is this circuit designed for USA or EU mains voltage (110/220V)?

2) Why does 4N25 need rectified input? I assume it's because the input is basically a LED which is polarised by definition?

3) How does the 4N25 generate a falling edge at zero crossing? I assume the phototransistor is saturated 99.9% of the time and only drops to zero when the input is very close to zero as well?

4) Can you please briefly explain the working of the Triac circuit around MOC3023M? Why have the resistors/capacitors been chosen the way they have?

Thanks so much,

Matthieu

**Comment by pmarchini** [comment]
Hey there!

Answering point by point : 

1. It's designed for EU mains voltage but I don't see any issue with 110V, the only difference is the configuration of the frequency from 50Hz to 60Hz
2. Yep, the reason is that is an optocoupler
3. Yep, it drops to zero when the AC voltage drops under the saturation level
4. MOC3023M it's a TRIAC driver, the resistors/capacitors values are following the default circuit suggested into the datasheet

Regarding your project I've ported this library from Arduino to ESP for a similar reason ( control temperature of a terrarium cutting the wave in order to reduce the output of a terrarium heater) and I'm still searching for some free time in order to develop my project.
In case you decide to opensource something I'm interested into contributing

**Comment by matsvandamme** [comment]
Can you be reached via Discord? Perhaps we can lay-out the ground work for a joint project. My Discord handle is matsvandamme#1863. Feel free to drop me a DM.

**Comment by pmarchini** [comment]
I'll send you a DM today !!!
